# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20180928_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='pub_date',
            new_name='post_date',
        ),
    ]
