# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20180928_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['pub_date']},
        ),
    ]
