# Generated by Django 2.1.2 on 2018-10-04 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20180930_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
